(() => {
  "use strict";
  const KEY="helen-arrangements-v1", $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const now=()=>new Date().toISOString(), esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
  function seed(){let order=0;return{schemaVersion:1,sectionOrder:window.HELEN_CHECKLIST.sections.map(s=>s.id),tasks:window.HELEN_CHECKLIST.sections.flatMap(sec=>sec.tasks.map((raw,i)=>{const x=typeof raw==="string"?{t:raw}:raw;return{id:`${sec.id}-${String(i+1).padStart(3,"0")}-${slug(x.t).slice(0,24)}`,title:x.t,section:sec.id,order:order++,status:x.done?"complete":"incomplete",priority:x.p||"normal",notes:x.n||"",decision:"",dueDate:"",completedDate:x.done?"2026-09-25":"",createdDate:"2026-09-25",lastUpdatedDate:"2026-09-25",contact:x.c||"",referenceNumber:x.r||"",amount:x.a||"",evidence:"",custom:false,history:[]}}))};}
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.schemaVersion===1&&Array.isArray(x.tasks))return x}catch(e){}return seed()}
  let state=load(), filter="all", query="", pendingDelete=null;
  const sections=window.HELEN_CHECKLIST.sections;
  function save(){const el=$("#saveState");el.textContent="Saving…";el.classList.add("saving");localStorage.setItem(KEY,JSON.stringify(state));setTimeout(()=>{el.textContent="Saved locally";el.classList.remove("saving")},220)}
  function sectionName(id){return sections.find(s=>s.id===id)?.title||id}
  function visible(t){const hay=[t.title,t.notes,t.contact,t.referenceNumber,t.decision,t.amount,t.evidence].join(" ").toLowerCase();const q=!query||hay.includes(query);const f=filter==="all"||(filter==="incomplete"&&t.status!=="complete")||(filter==="completed"&&t.status==="complete")||t.priority===filter;return q&&f}
  function priorityRank(p){return p==="urgent"?0:p==="attention"?1:2}
  function render(){renderProgress();renderNext();renderSections();}
  function renderProgress(){const n=state.tasks.length,c=state.tasks.filter(t=>t.status==="complete").length,p=n?Math.round(c/n*100):0;$("#progressText").textContent=`${c} / ${n} complete`;$("#percentText").textContent=`${p}%`;$("#progressBar").style.width=`${p}%`;$("#progressBar").parentElement.setAttribute("aria-label",`${p}% complete`)}
  function renderNext(){const next=state.tasks.filter(t=>t.status!=="complete").sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||a.order-b.order).slice(0,5);$("#nextList").innerHTML=next.length?next.map((t,i)=>`<div class="next-item"><span class="next-number">${String(i+1).padStart(2,"0")}</span><button data-open="${esc(t.id)}">${esc(t.title)}</button>${t.priority!=="normal"?`<span class="badge ${t.priority}">${t.priority}</span>`:""}</div>`).join(""):`<div class="next-item">Everything is complete.</div>`}
  function taskMeta(t){return[[t.decision&&`Decision: ${t.decision}`],[t.dueDate&&`Due ${fmt(t.dueDate)}`],[t.contact],[t.referenceNumber&&`Ref ${t.referenceNumber}`],[t.amount],[t.notes]].flat().filter(Boolean).slice(0,3).map(x=>`<span>${esc(x)}</span>`).join("")}
  function renderSections(){let shown=0;const html=state.sectionOrder.map(id=>{const sec=sections.find(s=>s.id===id)||{id,title:sectionName(id)};const all=state.tasks.filter(t=>t.section===id).sort((a,b)=>a.order-b.order),tasks=all.filter(visible);shown+=tasks.length;if(!tasks.length&&(query||filter!=="all"))return"";const done=all.filter(t=>t.status==="complete").length;return`<details class="check-section" data-section="${id}" ${id==="immediate"||id==="funeral"?"open":""}><summary><div class="section-title"><h3>${esc(sec.title)}</h3><small>${done} of ${all.length} complete</small></div><span class="section-progress">${all.length?Math.round(done/all.length*100):0}%</span><span class="chevron" aria-hidden="true"></span></summary>${sec.intro?`<p class="section-intro">${esc(sec.intro)}</p>`:""}<div class="tasks">${tasks.map(t=>taskHTML(t)).join("")||'<p class="empty">No tasks here yet.</p>'}</div><button class="section-add" data-add="${id}">+ Add task here</button></details>`}).join("");$("#checklist").innerHTML=html||'<div class="empty">No tasks match this search.</div>';$("#resultsNote").textContent=query||filter!=="all"?`${shown} matching task${shown===1?"":"s"}`:""}
  function taskHTML(t){const done=t.status==="complete";return`<div class="task-wrap" data-id="${esc(t.id)}"><div class="task ${done?"done":""}"><input type="checkbox" ${done?"checked":""} aria-label="Mark ${esc(t.title)} ${done?"incomplete":"complete"}" data-check="${esc(t.id)}"><div class="task-main"><div class="task-title"><span>${esc(t.title)}</span>${t.priority!=="normal"?`<span class="badge ${t.priority}">${t.priority}</span>`:""}</div>${taskMeta(t)?`<div class="task-meta">${taskMeta(t)}</div>`:""}</div><details class="task-menu"><summary aria-label="Actions for ${esc(t.title)}">•••</summary><div class="menu"><button data-edit="${esc(t.id)}">Edit details</button><button data-duplicate="${esc(t.id)}">Duplicate</button><button data-up="${esc(t.id)}">Move up</button><button data-down="${esc(t.id)}">Move down</button><button class="danger-text" data-delete="${esc(t.id)}">Delete</button></div></details></div><div class="insert"><button data-insert="${esc(t.id)}" aria-label="Add task after ${esc(t.title)}">+</button></div></div>`}
  function fmt(d){if(!d)return"";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(d+"T12:00:00"))}
  function toggle(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.status=t.status==="complete"?"incomplete":"complete";t.completedDate=t.status==="complete"?now():"";t.lastUpdatedDate=now();t.history.push({at:now(),event:t.status});save();render()}
  function openTask(id,section,afterId){const t=id&&state.tasks.find(x=>x.id===id);$("#taskForm").reset();$("#taskId").value=t?.id||"";$("#taskId").dataset.after=afterId||"";$("#dialogTitle").textContent=t?"Edit task":"Add task";$("#dialogEyebrow").textContent=t?sectionName(t.section):"New checklist item";$("#taskTitle").value=t?.title||"";$("#taskStatus").value=t?.status||"incomplete";$("#taskPriority").value=t?.priority||"normal";$("#taskSection").value=t?.section||section||"immediate";$("#taskDue").value=t?.dueDate||"";$("#taskDecision").value=t?.decision||"";$("#taskAmount").value=t?.amount||"";$("#taskContact").value=t?.contact||"";$("#taskReference").value=t?.referenceNumber||"";$("#taskNotes").value=t?.notes||"";$("#taskEvidence").value=t?.evidence||"";$("#taskDialog").showModal();setTimeout(()=>$("#taskTitle").focus(),40)}
  function saveTask(e){e.preventDefault();if(!$("#taskTitle").reportValidity())return;const id=$("#taskId").value, old=state.tasks.find(x=>x.id===id), section=$("#taskSection").value,after=$("#taskId").dataset.after;let order;if(old)order=old.order;else if(after){const a=state.tasks.find(x=>x.id===after);order=a.order+.5}else{const vals=state.tasks.filter(x=>x.section===section).map(x=>x.order);order=vals.length?Math.max(...vals)+1:state.tasks.length}const t={...(old||{}),id:old?.id||`custom-${Date.now()}`,title:$("#taskTitle").value.trim(),section,order,status:$("#taskStatus").value,priority:$("#taskPriority").value,notes:$("#taskNotes").value.trim(),decision:$("#taskDecision").value.trim(),dueDate:$("#taskDue").value,completedDate:$("#taskStatus").value==="complete"?(old?.completedDate||now()):"",createdDate:old?.createdDate||now(),lastUpdatedDate:now(),contact:$("#taskContact").value.trim(),referenceNumber:$("#taskReference").value.trim(),amount:$("#taskAmount").value.trim(),evidence:$("#taskEvidence").value.trim(),custom:true,history:[...(old?.history||[]),{at:now(),event:old?"edited":"created"}]};if(old)Object.assign(old,t);else state.tasks.push(t);normalize(section);save();$("#taskDialog").close();render()}
  function normalize(section){state.tasks.filter(t=>t.section===section).sort((a,b)=>a.order-b.order).forEach((t,i)=>t.order=i)}
  function move(id,delta){const t=state.tasks.find(x=>x.id===id),arr=state.tasks.filter(x=>x.section===t.section).sort((a,b)=>a.order-b.order),i=arr.indexOf(t),j=i+delta;if(j<0||j>=arr.length)return;[arr[i].order,arr[j].order]=[arr[j].order,arr[i].order];save();render()}
  function duplicate(id){const t=state.tasks.find(x=>x.id===id),copy={...t,id:`custom-${Date.now()}`,title:`${t.title} (copy)`,order:t.order+.5,status:"incomplete",completedDate:"",createdDate:now(),lastUpdatedDate:now(),custom:true,history:[{at:now(),event:"duplicated"}]};state.tasks.push(copy);normalize(t.section);save();render()}
  function remove(id){state.tasks=state.tasks.filter(t=>t.id!==id);save();render()}
  function download(name,type,content){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function exportJson(){download(`helen-arrangements-backup-${new Date().toISOString().slice(0,10)}.json`,"application/json",JSON.stringify({...state,exportedAt:now()},null,2))}
  function summary(important=false){const chosen=important?state.tasks.filter(t=>t.priority!=="normal"||t.decision||t.amount):state.tasks;const groups=state.sectionOrder.map(id=>({name:sectionName(id),tasks:chosen.filter(t=>t.section===id).sort((a,b)=>a.order-b.order)})).filter(g=>g.tasks.length);const html=`<!doctype html><html><head><meta charset="utf-8"><title>Helen Augsburger — ${important?"Important decisions & actions":"Executor working summary"}</title><style>body{font:15px/1.45 system-ui;max-width:900px;margin:40px auto;padding:0 20px;color:#18211e}h1{font-family:Georgia,serif;font-size:38px}h2{margin-top:32px;border-bottom:1px solid #ccc;padding-bottom:6px}li{margin:8px 0}.done{text-decoration:line-through;color:#68716d}.meta{color:#666;font-size:13px}.note{background:#f3f1ec;padding:12px;border-radius:8px}@media print{body{margin:0}}</style></head><body><h1>${important?"Important decisions & actions":"Arrangements"}</h1><p>Helen Augsburger / Phillips · Executor's working record · Exported ${esc(new Date().toLocaleString("en-GB"))}</p><p class="note">Working record only. This is not a formal legal document and does not determine ownership, liability, entitlement or tax treatment.</p>${groups.map(g=>`<h2>${esc(g.name)}</h2><ul>${g.tasks.map(t=>`<li class="${t.status==="complete"?"done":""}"><strong>${esc(t.title)}</strong> — ${t.status==="complete"?`completed ${esc(fmt(t.completedDate?.slice(0,10)))}`:"outstanding"}${[t.decision&&`Decision: ${t.decision}`,t.referenceNumber&&`Reference: ${t.referenceNumber}`,t.amount&&`Amount: ${t.amount}`,t.notes].filter(Boolean).length?`<div class="meta">${[t.decision&&`Decision: ${t.decision}`,t.referenceNumber&&`Reference: ${t.referenceNumber}`,t.amount&&`Amount: ${t.amount}`,t.notes].filter(Boolean).map(esc).join(" · ")}</div>`:""}</li>`).join("")}</ul>`).join("")}</body></html>`;download(`helen-${important?"important":"summary"}-${new Date().toISOString().slice(0,10)}.html`,"text/html",html)}
  async function importFile(file){let incoming;try{incoming=JSON.parse(await file.text())}catch(e){alert("That file is not valid JSON.");return}if(!incoming||incoming.schemaVersion!==1||!Array.isArray(incoming.tasks)||!incoming.tasks.every(t=>t.id&&t.title&&t.section)){alert("This is not a valid Helen arrangements backup.");return}if(confirm("Export your current checklist before replacing it?"))exportJson();if(!confirm(`Replace this checklist with ${incoming.tasks.length} imported tasks?`))return;state={schemaVersion:1,sectionOrder:Array.isArray(incoming.sectionOrder)?incoming.sectionOrder:sections.map(s=>s.id),tasks:incoming.tasks};save();render()}
  function setup(){$("#facts").innerHTML=window.HELEN_CHECKLIST.facts.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join("");$("#taskSection").innerHTML=sections.map(s=>`<option value="${s.id}">${esc(s.title)}</option>`).join("");const fs=["all","urgent","attention","incomplete","completed"];$("#filters").innerHTML=fs.map(x=>`<button class="filter ${x==="all"?"active":""}" data-filter="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join("");$("#infoToggle").onclick=()=>{const p=$("#infoPanel"),show=p.hidden;p.hidden=!show;$("#infoToggle").setAttribute("aria-expanded",show)};$("#search").oninput=e=>{query=e.target.value.trim().toLowerCase();renderSections()};$("#filters").onclick=e=>{const b=e.target.closest("[data-filter]");if(!b)return;filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderSections()};$("#checklist").onclick=e=>{const el=e.target.closest("[data-check],[data-edit],[data-duplicate],[data-up],[data-down],[data-delete],[data-insert],[data-add]");if(!el)return;if(el.dataset.check)toggle(el.dataset.check);else if(el.dataset.edit)openTask(el.dataset.edit);else if(el.dataset.duplicate)duplicate(el.dataset.duplicate);else if(el.dataset.up)move(el.dataset.up,-1);else if(el.dataset.down)move(el.dataset.down,1);else if(el.dataset.insert){const t=state.tasks.find(x=>x.id===el.dataset.insert);openTask(null,t.section,t.id)}else if(el.dataset.add)openTask(null,el.dataset.add);else if(el.dataset.delete){pendingDelete=el.dataset.delete;const t=state.tasks.find(x=>x.id===pendingDelete);$("#confirmText").textContent=`Delete “${t.title}”? This cannot be undone.`;$("#confirmDialog").showModal()}};$("#nextList").onclick=e=>{const b=e.target.closest("[data-open]");if(b)openTask(b.dataset.open)};$("#addSectionTask").onclick=()=>openTask(null,"immediate");$("#saveTask").onclick=saveTask;$("#confirmYes").onclick=()=>{if(pendingDelete)remove(pendingDelete);pendingDelete=null};$("#exportJson").onclick=exportJson;$("#importJson").onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]);e.target.value=""};$("#exportSummary").onclick=()=>summary(false);$("#exportImportant").onclick=()=>summary(true);$("#resetData").onclick=()=>{if(confirm("Export a backup before resetting?"))exportJson();if(confirm("Reset every task to the original checklist? All local changes will be removed.")){state=seed();save();render()}};render()}
  setup();
})();
