(() => {
  "use strict";
  const KEY="helen-arrangements-v1", $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const now=()=>new Date().toISOString(), esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
  const sections=window.HELEN_CHECKLIST.sections.filter(s=>s.id!=="michele");
  function seed(){let order=0;return{schemaVersion:1,sectionOrder:sections.map(s=>s.id),tasks:sections.flatMap(sec=>sec.tasks.map((raw,i)=>{const x=typeof raw==="string"?{t:raw}:raw;return{id:`${sec.id}-${String(i+1).padStart(3,"0")}-${slug(x.t).slice(0,24)}`,title:x.t,section:sec.id,order:order++,status:x.done?"complete":"incomplete",priority:x.p||"normal",notes:x.n||"",decision:"",dueDate:"",completedDate:x.done?"2026-09-25":"",createdDate:"2026-09-25",lastUpdatedDate:"2026-09-25",contact:x.c||"",referenceNumber:x.r||"",amount:x.a||"",evidence:"",custom:false,history:[]}}))};}
  function migrate(x){x.tasks=x.tasks.filter(t=>t.section!=="michele");x.sectionOrder=sections.map(s=>s.id);if((x.dataRevision||0)<2){const combine=(titles,title,extra={})=>{const found=x.tasks.filter(t=>t.section==="funeral"&&titles.includes(t.title));if(!found.length)return;const first=found.sort((a,b)=>a.order-b.order)[0];Object.assign(first,{title,status:found.some(t=>t.status==="complete")?"complete":"incomplete",completedDate:found.find(t=>t.completedDate)?.completedDate||"",notes:[...new Set(found.map(t=>t.notes).filter(Boolean))].join("\n"),lastUpdatedDate:now(),...extra});x.tasks=x.tasks.filter(t=>!found.some(f=>f.id===t.id)||t.id===first.id)};combine(["Choose entrance music","Choose reflection music","Choose exit music"],"Choose funeral music");combine(["Choose readers","Confirm readers"],"Choose and confirm readers");combine(["Decide wake location","Book wake venue"],"Choose and book wake venue");combine(["Choose wake food","Record dietary needs","Arrange wake catering","Choose wake drinks"],"Arrange wake food and drinks");combine(["Decide burial or cremation"],"Record Helen's cremation wish",{status:"complete",completedDate:now(),notes:"Helen wished to be cremated.",decision:"Cremation"});x.tasks=x.tasks.filter(t=>!["Check burial plot ownership","Choose crematorium or cemetery","Confirm burial paperwork"].includes(t.title));const crem=x.tasks.find(t=>t.title==="Choose crematorium");if(!crem){const anchor=x.tasks.find(t=>t.title==="Record Helen's cremation wish");x.tasks.push({...anchor,id:"funeral-choose-crematorium",title:"Choose crematorium",status:"incomplete",completedDate:"",notes:"",decision:"",order:(anchor?.order||0)+.1,lastUpdatedDate:now()})}x.dataRevision=2}return x}
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.schemaVersion===1&&Array.isArray(x.tasks))return migrate(x)}catch(e){}const x=seed();x.dataRevision=2;return x}
  let state=load(), filter="all", query="", pendingDelete=null, drag=null, passcode="", syncTimer=null;
  const openSections=new Set();
  function localSave(){localStorage.setItem(KEY,JSON.stringify(state))}
  function save(){const el=$("#saveState");state.updatedAt=now();localSave();el.textContent="Saving…";el.classList.add("saving");clearTimeout(syncTimer);syncTimer=setTimeout(syncRemote,350)}
  async function syncRemote(){const el=$("#saveState");if(!passcode){el.textContent="Saved on this device";el.classList.remove("saving");return}try{const res=await fetch("/api/helen-state",{method:"PUT",headers:{"Content-Type":"application/json","X-Helen-Passcode":passcode},body:JSON.stringify(state)});if(!res.ok)throw Error();el.textContent="Saved everywhere"}catch(e){el.textContent="Saved on this device"}el.classList.remove("saving")}
  async function loadRemote(){const el=$("#saveState");el.textContent="Syncing…";try{const res=await fetch("/api/helen-state",{headers:{"X-Helen-Passcode":passcode}});if(res.status===404){await syncRemote();return}if(!res.ok)throw Error();const remote=migrate(await res.json());const localTime=Date.parse(state.updatedAt||"1970-01-01"),remoteTime=Date.parse(remote.updatedAt||"1970-01-01");if(remoteTime>=localTime)state=remote;else await syncRemote();localSave();render();el.textContent="Saved everywhere"}catch(e){el.textContent="Saved on this device"}el.classList.remove("saving")}
  function sectionName(id){return sections.find(s=>s.id===id)?.title||id}
  function visible(t){const hay=[t.title,t.notes,t.contact,t.referenceNumber,t.decision,t.amount,t.evidence].join(" ").toLowerCase();const q=!query||hay.includes(query);const f=filter==="all"||(filter==="incomplete"&&t.status!=="complete")||(filter==="completed"&&t.status==="complete")||t.priority===filter;return q&&f}
  function priorityRank(p){return p==="urgent"?0:p==="attention"?1:2}
  function render(){renderProgress();renderNext();renderSections();}
  function renderProgress(){const n=state.tasks.length,c=state.tasks.filter(t=>t.status==="complete").length,p=n?Math.round(c/n*100):0;$("#progressText").textContent=`${c} / ${n} complete`;$("#percentText").textContent=`${p}%`;$("#progressBar").style.width=`${p}%`;$("#progressBar").parentElement.setAttribute("aria-label",`${p}% complete`)}
  function renderNext(){const next=state.tasks.filter(t=>t.status!=="complete").sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||a.order-b.order).slice(0,5);$("#nextList").innerHTML=next.length?next.map((t,i)=>`<div class="next-item"><span class="next-number">${String(i+1).padStart(2,"0")}</span><button data-open="${esc(t.id)}">${esc(t.title)}</button>${t.priority!=="normal"?`<span class="badge ${t.priority}">${t.priority}</span>`:""}</div>`).join(""):`<div class="next-item">Everything is complete.</div>`}
  function taskMeta(t){return[[t.decision&&`Decision: ${t.decision}`],[t.dueDate&&`Due ${fmt(t.dueDate)}`],[t.contact],[t.referenceNumber&&`Ref ${t.referenceNumber}`],[t.amount],[t.notes]].flat().filter(Boolean).slice(0,3).map(x=>`<span>${esc(x)}</span>`).join("")}
  function renderSections(){let shown=0;const html=state.sectionOrder.map(id=>{const sec=sections.find(s=>s.id===id)||{id,title:sectionName(id)};const all=state.tasks.filter(t=>t.section===id).sort((a,b)=>a.order-b.order),tasks=all.filter(visible);shown+=tasks.length;if(!tasks.length&&(query||filter!=="all"))return"";const done=all.filter(t=>t.status==="complete").length;return`<details class="check-section" data-section="${id}" ${openSections.has(id)?"open":""}><summary><div class="section-title"><h3>${esc(sec.title)}</h3><small>${done} of ${all.length} complete</small></div><span class="section-progress">${all.length?Math.round(done/all.length*100):0}%</span><span class="chevron" aria-hidden="true"></span></summary>${sec.intro?`<p class="section-intro">${esc(sec.intro)}</p>`:""}<div class="tasks">${tasks.map(t=>taskHTML(t)).join("")||'<p class="empty">No tasks here yet.</p>'}</div><button class="section-add" data-add="${id}">+ Add task here</button></details>`}).join("");$("#checklist").innerHTML=html||'<div class="empty">No tasks match this search.</div>';$("#resultsNote").textContent=query||filter!=="all"?`${shown} matching task${shown===1?"":"s"}`:""}
  function taskHTML(t){const done=t.status==="complete";return`<div class="task-wrap" data-id="${esc(t.id)}"><div class="task ${done?"done":""}"><button class="drag-handle" data-drag="${esc(t.id)}" aria-label="Drag ${esc(t.title)} to reorder" title="Drag to move">⠿</button><input type="checkbox" ${done?"checked":""} aria-label="Mark ${esc(t.title)} ${done?"incomplete":"complete"}" data-check="${esc(t.id)}"><div class="task-main"><div class="task-title"><span>${esc(t.title)}</span>${t.priority!=="normal"?`<span class="badge ${t.priority}">${t.priority}</span>`:""}</div>${taskMeta(t)?`<div class="task-meta">${taskMeta(t)}</div>`:""}</div><details class="task-menu"><summary aria-label="Actions for ${esc(t.title)}">•••</summary><div class="menu"><button data-edit="${esc(t.id)}">Edit details</button><button data-duplicate="${esc(t.id)}">Duplicate</button><button data-up="${esc(t.id)}">Move up</button><button data-down="${esc(t.id)}">Move down</button><button class="danger-text" data-delete="${esc(t.id)}">Delete</button></div></details></div><div class="insert"><button data-insert="${esc(t.id)}" aria-label="Add task after ${esc(t.title)}">+</button></div></div>`}
  function fmt(d){if(!d)return"";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(d+"T12:00:00"))}
  function toggle(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.status=t.status==="complete"?"incomplete":"complete";t.completedDate=t.status==="complete"?now():"";t.lastUpdatedDate=now();t.history.push({at:now(),event:t.status});save();render()}
  function openTask(id,section,afterId){const t=id&&state.tasks.find(x=>x.id===id);$("#taskForm").reset();$("#taskId").value=t?.id||"";$("#taskId").dataset.after=afterId||"";$("#dialogTitle").textContent=t?"Edit task":"Add task";$("#dialogEyebrow").textContent=t?sectionName(t.section):"New checklist item";$("#taskTitle").value=t?.title||"";$("#taskStatus").value=t?.status||"incomplete";$("#taskPriority").value=t?.priority||"normal";$("#taskSection").value=t?.section||section||"immediate";$("#taskDue").value=t?.dueDate||"";$("#taskDecision").value=t?.decision||"";$("#taskAmount").value=t?.amount||"";$("#taskContact").value=t?.contact||"";$("#taskReference").value=t?.referenceNumber||"";$("#taskNotes").value=t?.notes||"";$("#taskEvidence").value=t?.evidence||"";$("#taskDialog").showModal();setTimeout(()=>$("#taskTitle").focus(),40)}
  function saveTask(e){e.preventDefault();if(!$("#taskTitle").reportValidity())return;const id=$("#taskId").value, old=state.tasks.find(x=>x.id===id), section=$("#taskSection").value,after=$("#taskId").dataset.after;let order;if(old)order=old.order;else if(after){const a=state.tasks.find(x=>x.id===after);order=a.order+.5}else{const vals=state.tasks.filter(x=>x.section===section).map(x=>x.order);order=vals.length?Math.max(...vals)+1:state.tasks.length}const t={...(old||{}),id:old?.id||`custom-${Date.now()}`,title:$("#taskTitle").value.trim(),section,order,status:$("#taskStatus").value,priority:$("#taskPriority").value,notes:$("#taskNotes").value.trim(),decision:$("#taskDecision").value.trim(),dueDate:$("#taskDue").value,completedDate:$("#taskStatus").value==="complete"?(old?.completedDate||now()):"",createdDate:old?.createdDate||now(),lastUpdatedDate:now(),contact:$("#taskContact").value.trim(),referenceNumber:$("#taskReference").value.trim(),amount:$("#taskAmount").value.trim(),evidence:$("#taskEvidence").value.trim(),custom:true,history:[...(old?.history||[]),{at:now(),event:old?"edited":"created"}]};if(old)Object.assign(old,t);else state.tasks.push(t);normalize(section);save();$("#taskDialog").close();render()}
  function normalize(section){state.tasks.filter(t=>t.section===section).sort((a,b)=>a.order-b.order).forEach((t,i)=>t.order=i)}
  function clearDropMarks(){$$(".drop-before,.drop-after,.drop-section").forEach(el=>el.classList.remove("drop-before","drop-after","drop-section"))}
  function dragStart(e){const h=e.target.closest("[data-drag]");if(!h)return;e.preventDefault();const source=h.closest(".task-wrap");drag={id:h.dataset.drag,source,targetId:null,targetSection:null,before:true};source.classList.add("dragging");h.setPointerCapture?.(e.pointerId)}
  function dragMove(e){if(!drag)return;e.preventDefault();if(e.clientY<70)window.scrollBy(0,-14);else if(e.clientY>innerHeight-70)window.scrollBy(0,14);drag.source.style.visibility="hidden";const under=document.elementFromPoint(e.clientX,e.clientY);drag.source.style.visibility="";clearDropMarks();const target=under?.closest(".task-wrap");if(target&&target!==drag.source){const before=e.clientY<target.getBoundingClientRect().top+target.offsetHeight/2;target.classList.add(before?"drop-before":"drop-after");drag.targetId=target.dataset.id;drag.targetSection=state.tasks.find(t=>t.id===drag.targetId)?.section;drag.before=before}else{const section=under?.closest(".check-section");if(section){section.classList.add("drop-section");drag.targetId=null;drag.targetSection=section.dataset.section}}}
  function dragEnd(){if(!drag)return;const moved=state.tasks.find(t=>t.id===drag.id),oldSection=moved?.section,targetSection=drag.targetSection;if(moved&&targetSection){const list=state.tasks.filter(t=>t.section===targetSection&&t.id!==moved.id).sort((a,b)=>a.order-b.order);let index=list.length;if(drag.targetId){const targetIndex=list.findIndex(t=>t.id===drag.targetId);index=targetIndex+(drag.before?0:1)}moved.section=targetSection;list.splice(index,0,moved);list.forEach((t,i)=>t.order=i);if(oldSection!==targetSection)normalize(oldSection);moved.lastUpdatedDate=now();moved.history.push({at:now(),event:`moved to ${sectionName(targetSection)}`});save()}clearDropMarks();drag.source.classList.remove("dragging");drag=null;render()}
  function move(id,delta){const t=state.tasks.find(x=>x.id===id),arr=state.tasks.filter(x=>x.section===t.section).sort((a,b)=>a.order-b.order),i=arr.indexOf(t),j=i+delta;if(j<0||j>=arr.length)return;[arr[i].order,arr[j].order]=[arr[j].order,arr[i].order];save();render()}
  function duplicate(id){const t=state.tasks.find(x=>x.id===id),copy={...t,id:`custom-${Date.now()}`,title:`${t.title} (copy)`,order:t.order+.5,status:"incomplete",completedDate:"",createdDate:now(),lastUpdatedDate:now(),custom:true,history:[{at:now(),event:"duplicated"}]};state.tasks.push(copy);normalize(t.section);save();render()}
  function remove(id){state.tasks=state.tasks.filter(t=>t.id!==id);save();render()}
  function download(name,type,content){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function exportJson(){download(`helen-arrangements-backup-${new Date().toISOString().slice(0,10)}.json`,"application/json",JSON.stringify({...state,exportedAt:now()},null,2))}
  function summary(important=false){const chosen=important?state.tasks.filter(t=>t.priority!=="normal"||t.decision||t.amount):state.tasks;const groups=state.sectionOrder.map(id=>({name:sectionName(id),tasks:chosen.filter(t=>t.section===id).sort((a,b)=>a.order-b.order)})).filter(g=>g.tasks.length);const html=`<!doctype html><html><head><meta charset="utf-8"><title>Helen Augsburger — ${important?"Important decisions & actions":"Executor working summary"}</title><style>body{font:15px/1.45 system-ui;max-width:900px;margin:40px auto;padding:0 20px;color:#18211e}h1{font-family:Georgia,serif;font-size:38px}h2{margin-top:32px;border-bottom:1px solid #ccc;padding-bottom:6px}li{margin:8px 0}.done{text-decoration:line-through;color:#68716d}.meta{color:#666;font-size:13px}.note{background:#f3f1ec;padding:12px;border-radius:8px}@media print{body{margin:0}}</style></head><body><h1>${important?"Important decisions & actions":"Arrangements"}</h1><p>Helen Augsburger / Phillips · Executor's working record · Exported ${esc(new Date().toLocaleString("en-GB"))}</p><p class="note">Working record only. This is not a formal legal document and does not determine ownership, liability, entitlement or tax treatment.</p>${groups.map(g=>`<h2>${esc(g.name)}</h2><ul>${g.tasks.map(t=>`<li class="${t.status==="complete"?"done":""}"><strong>${esc(t.title)}</strong> — ${t.status==="complete"?`completed ${esc(fmt(t.completedDate?.slice(0,10)))}`:"outstanding"}${[t.decision&&`Decision: ${t.decision}`,t.referenceNumber&&`Reference: ${t.referenceNumber}`,t.amount&&`Amount: ${t.amount}`,t.notes].filter(Boolean).length?`<div class="meta">${[t.decision&&`Decision: ${t.decision}`,t.referenceNumber&&`Reference: ${t.referenceNumber}`,t.amount&&`Amount: ${t.amount}`,t.notes].filter(Boolean).map(esc).join(" · ")}</div>`:""}</li>`).join("")}</ul>`).join("")}</body></html>`;download(`helen-${important?"important":"summary"}-${new Date().toISOString().slice(0,10)}.html`,"text/html",html)}
  async function importFile(file){let incoming;try{incoming=JSON.parse(await file.text())}catch(e){alert("That file is not valid JSON.");return}if(!incoming||incoming.schemaVersion!==1||!Array.isArray(incoming.tasks)||!incoming.tasks.every(t=>t.id&&t.title&&t.section)){alert("This is not a valid Helen arrangements backup.");return}if(confirm("Export your current checklist before replacing it?"))exportJson();if(!confirm(`Replace this checklist with ${incoming.tasks.length} imported tasks?`))return;state={schemaVersion:1,sectionOrder:Array.isArray(incoming.sectionOrder)?incoming.sectionOrder:sections.map(s=>s.id),tasks:incoming.tasks};save();render()}
  function setup(){$("#facts").innerHTML=window.HELEN_CHECKLIST.facts.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join("");$("#taskSection").innerHTML=sections.map(s=>`<option value="${s.id}">${esc(s.title)}</option>`).join("");const fs=["all","urgent","attention","incomplete","completed"];$("#filters").innerHTML=fs.map(x=>`<button class="filter ${x==="all"?"active":""}" data-filter="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join("");$("#infoToggle").onclick=()=>{const p=$("#infoPanel"),show=p.hidden;p.hidden=!show;$("#infoToggle").setAttribute("aria-expanded",show)};$("#search").oninput=e=>{query=e.target.value.trim().toLowerCase();renderSections()};$("#filters").onclick=e=>{const b=e.target.closest("[data-filter]");if(!b)return;filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderSections()};$("#checklist").addEventListener("toggle",e=>{if(!e.target.matches(".check-section"))return;e.target.open?openSections.add(e.target.dataset.section):openSections.delete(e.target.dataset.section)},true);$("#checklist").onclick=e=>{const el=e.target.closest("[data-check],[data-edit],[data-duplicate],[data-up],[data-down],[data-delete],[data-insert],[data-add]");if(!el)return;if(el.dataset.check)toggle(el.dataset.check);else if(el.dataset.edit)openTask(el.dataset.edit);else if(el.dataset.duplicate)duplicate(el.dataset.duplicate);else if(el.dataset.up)move(el.dataset.up,-1);else if(el.dataset.down)move(el.dataset.down,1);else if(el.dataset.insert){const t=state.tasks.find(x=>x.id===el.dataset.insert);openTask(null,t.section,t.id)}else if(el.dataset.add)openTask(null,el.dataset.add);else if(el.dataset.delete){pendingDelete=el.dataset.delete;const t=state.tasks.find(x=>x.id===pendingDelete);$("#confirmText").textContent=`Delete “${t.title}”? This cannot be undone.`;$("#confirmDialog").showModal()}};$("#checklist").addEventListener("pointerdown",dragStart);window.addEventListener("pointermove",dragMove,{passive:false});window.addEventListener("pointerup",dragEnd);window.addEventListener("pointercancel",dragEnd);$("#nextList").onclick=e=>{const b=e.target.closest("[data-open]");if(b)openTask(b.dataset.open)};$("#addSectionTask").onclick=()=>openTask(null,"immediate");$("#saveTask").onclick=saveTask;$("#confirmYes").onclick=()=>{if(pendingDelete)remove(pendingDelete);pendingDelete=null};$("#exportJson").onclick=exportJson;$("#importJson").onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]);e.target.value=""};$("#exportSummary").onclick=()=>summary(false);$("#exportImportant").onclick=()=>summary(true);$("#resetData").onclick=()=>{if(confirm("Export a backup before resetting?"))exportJson();if(confirm("Reset every task to the original checklist? All local changes will be removed.")){state=seed();state.dataRevision=2;save();render()}};localSave();render()}
  async function passwordHash(value){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
  function unlock(){document.body.classList.remove("locked");$("#lockScreen").hidden=true;$("#appShell").hidden=false;setup()}
  async function authenticate(e){e?.preventDefault();const input=$("#passcode"),button=$("#lockForm button");button.disabled=true;const valid=await passwordHash(input.value)==="c77639710bd89eea8855346472b0eb9175987e0eaeb35df92b1712ca09215f05";button.disabled=false;if(valid){passcode=input.value;unlock();await loadRemote()}else{$("#lockError").textContent="That code is not correct.";input.value="";input.focus()}}
  $("#lockForm").addEventListener("submit",authenticate);
})();
