/* Helen's Arrangements — editable default checklist. Short strings become tasks;
   objects add priority, context and verified reference data. */
window.HELEN_CHECKLIST = {
  schemaVersion: 1,
  createdDate: "2026-09-25",
  facts: [
    ["Helen", "Helen Augsburger / Phillips"],
    ["Executor", "James (son; executor named in will)"],
    ["Home", "11 Beebys Way, Hampton Water, Peterborough PE7 8QU"],
    ["Current status", "Death is with the coroner; registration follows coroner clearance"],
    ["Embark pension", "A1072890 · 0344 544 0566"],
    ["Council tax", "502658896 · 01733 452258"],
    ["British Gas", "A39097102"],
    ["Leeds mortgage case", "73613086 (offer reference; live account unknown)"],
    ["EDF/LCS dispute", "45130947 · client 671185751595 · £417.77 disputed"],
    ["NatWest HR", "karolina.minczuk@natwest.com"],
    ["NatWest contact", "Matthew Bessent · 07786 703476"],
    ["Volvo contact", "christopher.hills@marshall.co.uk"],
  ],
  sections: [
    { id:"immediate", title:"Immediate & coroner", intro:"The death is with the coroner. Registration deadlines do not run in the normal way while clearance is outstanding.", tasks:[
      {t:"Record coroner case reference",p:"urgent"},{t:"Record coroner officer contact",p:"urgent"},{t:"Confirm post-mortem decision",p:"urgent"},{t:"Ask when body may release",p:"urgent"},{t:"Ask about interim certificate",p:"attention"},
      "Record coroner update dates","Save every coroner letter","Record Addenbrooke's contact","Collect remaining hospital paperwork","Confirm belongings already received","List hospital belongings received","Check valuables receipt","Choose family update contact","Create secure document folder","Start executor contact log","Record Helen's legal names","Record date and place of death","Record National Insurance number","Record NHS number","Identify immediate dependants","Secure medicines for return","Return medicines to pharmacy","Check pets and daily care","Tell close family personally","Identify people needing support"
    ]},
    { id:"funeral", title:"Funeral", intro:"Optional elements are decisions, not assumptions. The funeral director can confirm the forms required after coroner release.", tasks:[
      {t:"Review Helen's funeral wishes",p:"urgent"},{t:"Check will for funeral wishes",p:"urgent"},{t:"Ask family about known wishes",p:"attention"},{t:"Choose funeral director",p:"urgent"},{t:"Contact funeral director",p:"urgent"},
      "Confirm funeral director availability","Confirm care of Helen","Decide whether to visit Helen","Choose clothing for Helen","Deliver clothing to funeral director","Decide burial or cremation","Check burial plot ownership","Choose crematorium or cemetery","Confirm venue availability","Choose funeral date","Choose funeral time","Confirm coroner release first","Confirm cremation paperwork","Sign cremation application","Confirm burial paperwork","Choose coffin or casket","Choose coffin finish","Choose coffin fittings","Confirm coffin price","Decide hearse requirement","Decide family transport","Book family transport","Plan parking arrangements","Plan accessible arrival","Choose pallbearers","Confirm pallbearer availability","Choose officiant or celebrant","Meet officiant or celebrant","Share Helen's life details","Choose ceremony structure","Choose entrance music","Choose reflection music","Choose exit music","Check venue music rules","Choose readings","Choose readers","Confirm readers","Choose eulogy speaker","Draft eulogy","Review eulogy with family","Decide prayers or reflection","Choose funeral flowers","Choose floral message","Order funeral flowers","Decide charitable donations","Choose donation charity","Set up donation method","Write obituary or notice","Choose notice photograph","Publish death notice","Make funeral guest list","Send funeral details","Track guest responses","Estimate funeral attendance","Decide livestream","Arrange livestream","Test livestream access","Plan hearing accessibility","Plan mobility accessibility","Choose ceremony photograph","Choose slideshow photographs","Decide slideshow","Create slideshow","Test slideshow","Write order of service","Choose cover photograph","Collect order content","Approve order proof","Confirm print quantity","Collect printed orders","Decide wake location","Book wake venue","Estimate wake attendance","Choose wake food","Record dietary needs","Arrange wake catering","Choose wake drinks","Arrange wake music","Plan wake accessibility","Send wake details","Choose memory table items","Prepare memory table","Confirm funeral invoice","Check itemised funeral costs","Choose payment source","Record funeral payment","Save funeral invoice","Save funeral receipt","Confirm donations collected","Send thank-you messages","Collect ashes","Record ashes collection","Choose temporary ashes storage","Decide scattering or interment","Choose ashes location","Check landowner permission","Plan ashes gathering","Decide memorial type","Choose memorial wording","Approve memorial proof","Record memorial payment"
    ]},
    { id:"registration", title:"Registration & government", tasks:[
      {t:"Wait for coroner clearance",p:"urgent"},{t:"Record registrar contact",p:"urgent"},{t:"Book registration appointment",p:"urgent"},"Gather registration information","Confirm who will register","Register Helen's death","Check certificate details","Buy enough certified certificates","Record certificate serial numbers","Scan certificate working copies","Store certificates securely","Request Tell Us Once reference","Gather Tell Us Once details","Use Tell Us Once within deadline","Save Tell Us Once confirmation","Record notified organisations","Check HMRC notification","Check DWP notification","Check State Pension status","Check passport cancellation","Check driving licence cancellation","Check vehicle keeper updates","Check electoral register update","Return Blue Badge if required","Notify any public pension separately","Follow up missing government replies"
    ]},
    { id:"will", title:"Will & executors", tasks:[
      {t:"Secure original will",done:true},{t:"Record will storage location",p:"attention"},{t:"Read executor appointment",p:"attention"},"Record all executors","Contact co-executors","Agree lead executor","Record executor decisions","Identify beneficiaries","Record beneficiary contacts","Review specific gifts","Review residue instructions","Review funeral wishes separately","Check codicils","Check later will evidence","Avoid marking original will","Make certified working copy","Decide whether solicitor needed","Choose estate solicitor","Record solicitor engagement terms","Store sensitive copies securely","Limit access to estate records"
    ]},
    { id:"banking", title:"Banking & credit", tasks:[
      {t:"Secure all bank cards",p:"urgent"},{t:"Photograph card identifiers safely",p:"attention"},"List known bank accounts","Review twelve months statements","Identify incoming payments","Identify recurring payments","Identify outstanding direct debits","Identify unknown accounts","Use account tracing if needed","Open executor correspondence file",
      {t:"Contact NatWest bereavement team",p:"urgent",c:"Matthew Bessent · matthew.bessent@natwest.com · 07786 703476"},"Identify all NatWest accounts","Confirm NatWest date-of-death balances","Confirm NatWest interest to death","Record NatWest bereavement reference","Cancel NatWest Premier debit card","Check Premier linked benefits","Check DragonPass linkage","Notify NatWest Black credit","Request Black card final statement","Confirm Black card balance","Stop Black card recurring charges","Notify Barclaycard bereavement team","Request Barclaycard final statement","Confirm Barclaycard balance","Stop Barclaycard recurring charges","Notify Starling bereavement team","Identify all Starling accounts","Confirm Starling date-of-death balances","Download available statements","Record each account closure","Reconcile post-death transactions","Record interest after death","Keep account funds untouched","Consider dedicated estate account","Open estate account if needed"
    ]},
    { id:"pensions", title:"Pensions & investments", tasks:[
      {t:"Find Embark policy correspondence",p:"urgent",r:"A1072890"},{t:"Contact Embark bereavement team",p:"urgent",c:"customerservices@embarkpensions.co.uk · 0344 544 0566",r:"A1072890"},"Provide certificate to Embark","Request Embark death-date valuation","Request beneficiary nomination details","Request pension transaction history","Check pending lump-sum withdrawal","Reconcile withdrawal against balance","Confirm benefit claim process","Confirm estate treatment evidence","Record Embark claim reference","Record Embark response","Record benefit recipient decision","Record Embark payment",
      {t:"Find interactive investor account",p:"attention",n:"Project-recorded £10,220.32 is not a death-date value."},"Find interactive investor number","Notify interactive investor","Request ISA death-date valuation","Request ISA transaction history","Confirm continuing ISA treatment","Record interactive investor response","Reconcile ISA proceeds",
      "Find NS&I holder number","Notify NS&I of death","Request Premium Bonds valuation","Check post-death prize treatment","Record NS&I claim reference","Reconcile NS&I proceeds",
      {t:"Find EquatePlus plan reference",p:"attention",n:"£26,316.02 and 3,844 options are historical/project-recorded; confirm entitlement."},"Notify EquatePlus administrator","Request Sharesave death-date statement","Confirm option treatment","Confirm savings treatment","Check ISA transfer history","Reconcile Sharesave and ISA","Record Sharesave proceeds",
      "Find Lloyds pension correspondence","Identify Lloyds scheme administrator","Confirm scheme name and membership","Notify Lloyds pension administrator","Request benefit details","Request beneficiary process","Record Lloyds pension decision","Check for other pension schemes","Use Pension Tracing Service if needed"
    ]},
    { id:"employment", title:"Work — NatWest", tasks:[
      {t:"Continue contact with NatWest HR",p:"urgent",c:"karolina.minczuk@natwest.com"},"Confirm employment status at death","Request final salary calculation","Check unpaid salary","Check accrued holiday pay","Check outstanding expenses","Check employee benefits","Ask about disability-cover impact","Confirm death-in-service entitlement","Identify death-in-service administrator","Request death-in-service claim forms","Identify workplace pension administrator","Confirm Sharesave treatment","Check other employee share schemes","Check employee insurance benefits","List employer equipment","Return employer laptop","Return security passes","Resolve employer accounts access","Obtain final payslip","Obtain P45 if applicable","Record every employment payment","Reconcile payments to statements","Save HR correspondence"
    ]},
    { id:"house", title:"House — 11 Beebys Way", tasks:[
      {t:"Secure every external door",p:"urgent"},{t:"Secure every window",p:"urgent"},"Locate spare keys","Identify every key holder","Change locks if necessary","Check alarm status","Record alarm provider","Avoid sharing alarm codes","Check smoke alarms","Check carbon monoxide alarms","Photograph every room","Photograph valuable possessions","Start room-by-room inventory","Keep possessions at house initially","Identify items held elsewhere","Document jewellery custodian","Request jewellery inventory","Photograph recovered jewellery","Establish jewellery estate treatment","Record meter readings","Photograph gas meter","Photograph electricity meter","Photograph water meter","Collect and secure post","Create post review routine","Redirect post if appropriate","Empty perishable fridge items","Check freezer contents","Arrange bin collections","Set safe heating level","Record thermostat setting","Check for water leaks","Check stopcock location","Check garden maintenance","Cancel unwanted deliveries","Pause newspapers and milk","Check doorbell camera access","Check home security cover","Ask neighbour to monitor house","Log every property visit","Keep visit receipts","Avoid premature possessions distribution","Plan regular property checks"
    ]},
    { id:"utilities", title:"Utilities & household accounts", tasks:[
      {t:"Find home insurance policy",p:"urgent"},{t:"Notify home insurer",p:"urgent"},{t:"Confirm unoccupied-home conditions",p:"urgent"},"Record insurer claim reference","Follow required property checks","Confirm buildings cover","Confirm contents cover","Record policy renewal date",
      {t:"Contact British Gas bereavement",p:"attention",r:"A39097102",n:"June figures were historical: £148.82 credit and proposed £121.30 refund."},"Provide British Gas meter readings","Request death-date energy statement","Check historical £121.30 refund","Confirm ongoing energy supply","Change payment arrangement safely","Record British Gas response",
      "Find Anglian Water account number","Contact Anglian Water bereavement","Provide water meter reading","Request death-date water statement","Confirm ongoing water supply","Record Anglian Water response",
      {t:"Identify Vodafone account services",p:"attention",r:"Account ending 0528",n:"August bill showed £30 due 7 September; broadband versus mobile needs confirmation."},"Find full Vodafone account number","Contact Vodafone bereavement","Check September Vodafone payment","Decide whether broadband remains","Preserve service during administration","Record Vodafone response",
      {t:"Notify Peterborough council tax",p:"attention",r:"502658896",c:"local.taxation@peterborough.gov.uk · 01733 452258"},"Request updated council account","Confirm payments already received","Ask about applicable property change","Record council tax adjustment","Check TV Licence status","Notify TV Licensing if needed","Check paid household subscriptions","Cancel only unnecessary subscriptions","Record cancellation refunds"
    ]},
    { id:"property", title:"Property & mortgage", tasks:[
      {t:"Confirm legal property ownership",p:"attention"},"Obtain Land Registry title","Check joint ownership form","Identify secured property","Find completion statement","Find signed mortgage deed",
      {t:"Contact Leeds Building Society",p:"attention",r:"Offer case 73613086"},"Find live mortgage account number","Request death-date mortgage balance","Request mortgage transaction history","Confirm interest treatment","Confirm payment expectations","Request estate redemption process","Save lender response","Contact broker Ben Franklin","Request broker file","Record £199 broker fee evidence","Contact Setfords conveyancers","Request completed conveyancing file","Check Stacey Bell correspondence","Check Rachel Ward correspondence","Review former-home file A6409/3","Arrange independent property valuation","Record valuation basis and date","Maintain property insurance","Decide eventual sale or transfer","Check will before property decision","Wait for required probate authority","Record sale or transfer costs"
    ]},
    { id:"digital", title:"Phone, computer & digital life", tasks:[
      {t:"Secure Helen's phone",p:"urgent"},{t:"Keep phone charged",p:"urgent"},{t:"Preserve phone SIM",p:"urgent"},"Identify mobile provider","Preserve phone number initially","Record phone contract","Document device ownership","Secure Helen's computer","Back up important devices","Identify Apple or Google account","Use official legacy-account process","Preserve BT email access","Record BT account details","Preserve important emails","Export key estate emails","Do not delete relevant data","Identify password manager","Follow lawful access procedures","Inventory digital subscriptions","Identify cloud storage","Preserve family photographs","Back up important photographs","Preserve important documents","Review social accounts later","Decide memorialisation or deletion","Download allowed social data","Record digital account decisions","Decide eventual device disposal","Erase devices only when authorised"
    ]},
    { id:"vehicles", title:"Vehicles", tasks:[
      "List every owned vehicle","List every leased vehicle","Record registration numbers","Secure vehicle keys","Find V5C documents","Identify vehicle insurance","Notify vehicle insurer","Confirm vehicle ownership","Confirm vehicle finance","Record mileage and condition",
      {t:"Contact Marshall Volvo",p:"urgent",c:"Chris Hills · christopher.hills@marshall.co.uk"},{t:"Contact Motability bereavement",p:"urgent",c:"0300 456 4566"},"Obtain signed Volvo order","Record Volvo order reference","Confirm Volvo collection status","Confirm Motability lease status","Obtain payment receipts","Request written transaction breakdown","Confirm Lexus part-exchange ownership","Obtain Lexus valuation","Obtain Lexus finance settlement","Confirm cash returned to Helen","Confirm money allocated to Volvo","Confirm dealer still holds Lexus","Confirm deposit classification","Establish refund due","Request written settlement","Reconcile all vehicle payments","Avoid double-counting Lexus proceeds","Record vehicle refund receipt","Update DVLA keeper details","Decide remaining vehicle disposal"
    ]},
    { id:"refunds", title:"Refunds & money owed", tasks:[
      {t:"Check John Lewis refund",p:"attention",r:"Order 568200118",a:"£99.99 promised (historical)"},"Find refund destination account","Request John Lewis evidence","Confirm John Lewis receipt",
      {t:"Check Destination2 cancellation",p:"attention",r:"Booking 262052",c:"CustomerServices@destination2.co.uk"},"Request Destination2 outcome","Record travel refund amount","Record expected refund destination","Confirm travel refund receipt",
      "Track British Gas refund separately","Track employment payments separately","Track vehicle refunds separately","Identify insurance refunds","Identify subscription refunds","Review card chargebacks","Record each expected refund","Save refund correspondence","Confirm each refund on statement","Escalate overdue refunds","Avoid counting received refunds twice"
    ]},
    { id:"liabilities", title:"Debts & liabilities", intro:"Historical demands are leads, not proof. Validate each liability before payment.", tasks:[
      "Create liability register","Separate secured liabilities","Separate unsecured liabilities","Request evidence for every debt","Record creditor contact details","Record claimed balance date","Check post-death interest","Check direct-debit payments","Reject duplicate demands","Pay only validated liabilities","Save settlement evidence","Check mortgage liability","Check each credit-card liability","Check utility final bills","Check council tax balance",
      {t:"Preserve EDF/LCS dispute chain",p:"urgent",r:"LCS 45130947 · EDF 671185751595",a:"£417.77 disputed",n:"Helen did not accept this amount. Preserve edf.pdf and the 17, 21 and 26 April correspondence."},"Save EDF dispute attachment","Contact LCS for current status","Request itemised EDF charges","Request meter readings and tariffs","Confirm collection remains suspended","Record standing-charge evidence","Do not admit disputed liability","Decide dispute response with advice","Check former-address liabilities","Search for unknown creditors","Consider Gazette creditor notice","Wait creditor-notice period","Record every liability payment"
    ]},
    { id:"possessions", title:"Personal possessions", tasks:[
      "Create possessions inventory","Assign each item stable number","Photograph valuable jewellery","Value significant jewellery","Document safeguarded jewellery","Record jewellery custodian","Establish jewellery ownership","Inventory family photographs","Digitise fragile photographs","Inventory important documents","Inventory electronics","Record device serial numbers","Inventory furniture","Inventory clothing","Identify sentimental possessions","Record each beneficiary wish","Identify loaned-out items","Identify others' belongings","Return verified third-party items","Store valuables securely","Obtain specialist valuations","Check specific gifts in will","Avoid early distribution","Record every possession decision","Record every item transfer","Obtain recipient receipts","Donate only authorised items","Record donation receipts","Dispose only authorised items","Preserve important family records"
    ]},
    { id:"michele", title:"Michele Di Meglio handover", intro:"Separate from Helen's estate. The goal is a safe transfer of Michele's records and responsibilities—not ongoing administration by James.", tasks:[
      {t:"Keep Michele records separate",p:"urgent"},{t:"Agree handover recipient",p:"urgent"},"Agree secure handover method","Create handover inventory","Record handover date","Obtain Michele's receipt","Record unresolved mixed matters",
      "Confirm Luna Bianca company details","Record company 09763131","Record Corporation Tax UTR","Record VAT number 240949790","Contact Dennis & Pellizzaro","Share accountant record index","Confirm accountant fee proposal","Check invoice 8439 status","Check £500.84 tax refund receipt","Confirm MTD quarter submission","Confirm June–August VAT filing","Confirm July–September records handover","Confirm confirmation statement filed","Remind Michele about identity verification",
      "Record Gibraltar rates account 3677400","Confirm July rates payment","Confirm recurring rates arrangement","Record AquaGib account 10021160","Request current AquaGib statement","Record EuroCity reference EEM251","Record invoice IR002883","Request current Bentley statement","Confirm service-charge standing order","Share Gibraltar solicitor correspondence","Confirm property ownership advice status",
      "Handover 13 Winsover records","Record property reference 70230740","Record Flat 1 account 70230739","Record 13a reference 70521957","Locate final signed Winsover lease","Confirm Winsover insurance","Confirm Winsover gas certificate","Confirm council records updated","Handover 1 Lynwood records","Confirm Lynwood policy","Confirm Lynwood tenancy","Confirm Lynwood current rent","Handover 2 Swallowfield records","Confirm Swallowfield tenancy","Confirm deposit protection","Confirm Swallowfield insurance","Handover 11 South Street records","Confirm South Street policy","Confirm South Street payment","Handover 741 Lincoln Road records","Locate final Lincoln Road lease","Confirm Lincoln Road insurance",
      {t:"Handover Tower Street claim",p:"attention",c:"rbaxter@marlowgardner.co.uk · 01733 306703"},"Obtain Tower Street final invoice","Confirm Tower Street BACS payment","Record Tower Street excess","Handover 79 Braybrook matter","Record claim N1PP7231","Record references FK/4454 and PB/4454","Clarify estate involvement in Braybrook","Handover Crowland sale records","Obtain Crowland completion statement","Reconcile Crowland destination account","Clarify estate interest in proceeds","Handover V12 agreement 23484329","Confirm V12 current balance",
      {t:"Preserve BT Michele folders",p:"attention"},"Review Michele — Confirmed folder","Review Michele — Review folder","Document broad search limitations","Preserve local large-message folder","Include 79 Braybrook local email","Back up local Mail folder","Verify USB archive readability","Handover USB archive safely","Explain archive START HERE file","Mention four encrypted PDFs","Mention Photos Library not searched","Retain archive checksum evidence","Keep Helen estate emails separate","Stop acting after accepted handover"
    ]},
    { id:"records", title:"Records & evidence", tasks:[
      "Create estate document index","Save death certificates","Preserve original will","Retain provider letters","Save important emails","Export attachments with emails","Save date-of-death statements","Save invoices","Retain every receipt","Log every telephone call","Record representative names","Record contact dates","Record reference numbers","Record decisions and reasons","Record every payment","Record every refund","Record evidence source","Mark facts needing confirmation","Mark historical figures clearly","Mark disputed claims clearly","Back up estate records","Encrypt sensitive backups","Keep one off-device backup","Review backup monthly","Retain proof of distribution","Produce final estate accounts"
    ]},
    { id:"probate", title:"Estate, probate & tax", tasks:[
      {t:"Build complete asset register",p:"attention"},{t:"Obtain death-date valuations",p:"attention"},"Build complete liability register","Identify jointly owned assets","Identify assets passing by survivorship","Identify assets outside estate","Confirm pension benefit treatment","Confirm death-in-service treatment","Check gifts within seven years","Record foreign assets","Record trust interests","Calculate gross estate estimate","Calculate net estate estimate","Calculate probate values","Check whether probate is required","Check each provider's threshold","Establish Inheritance Tax position","Use official IHT checker","Decide whether IHT400 required","Complete required HMRC steps","Arrange tax payment if required","Save HMRC unique code","Choose probate applicants","Gather applicant details","Complete probate application","Send original will when required","Record probate application reference","Track probate application","Respond to probate queries","Record grant date","Store grant securely","Send grant copies to providers","Collect estate assets","Record estate income after death","Check estate Income Tax","Check final lifetime Income Tax","Claim any tax refund","Settle validated liabilities","Prepare draft estate accounts","Reconcile estate account","Share accounts for approval","Record required approvals","Distribute according to will","Retain administration records"
    ]},
    { id:"memberships", title:"Memberships & everyday accounts", tasks:[
      "Find Costco membership number","Notify Costco membership desk","Stop Costco renewal","Check Costco fee refund","Check Costco rewards","Check additional cardholder","Confirm DragonPass provider","Cancel DragonPass if separate","Confirm Clubcard ownership","Check Clubcard points","Check Clubcard vouchers","Check paid Tesco subscription","Request permitted points transfer","List other loyalty cards","Prioritise paid memberships","Cancel paid memberships safely","Record every membership outcome"
    ]},
    { id:"final", title:"Final administration", tasks:[
      "Confirm all assets collected","Confirm all creditors resolved","Confirm all disputes resolved","Confirm all refunds received","Confirm all taxes settled","Confirm funeral costs settled","Confirm estate income recorded","Complete final estate accounts","Obtain executor approvals","Obtain beneficiary approvals","Distribute remaining estate","Obtain beneficiary receipts","Close estate bank account","Finalise property sale or transfer","Finalise mortgage","Finalise possessions","Close remaining services","Close remaining digital accounts","Archive administration documents","Decide document retention dates","Store original will and grant","Preserve important family records","Provide beneficiaries final summary","Record administration completion date"
    ]}
  ]
};
